

spring:
  # 数据库配置
  profiles:
    include:
      - mybatisplus
  datasource:
    jmx-enabled: false
    name: moses_zoneconf
    url: jdbc:mysql://mysql-dev:3306/moses_zoneconf?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: moses_lixc
    password: 6qwOmLVhxUAK
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      # encrypt password
      filters: config,stat,wall,log4j
      connection-properties: "config.decrypt=true;config.decrypt.key=${app.datasource.druid.public-key};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
      use-global-data-source-stat: true

logging:
  level:
    com.chun.proxy: debug

